### ISSUE TITLE
챕터 1 : 컴퓨터 시스템의 개요

### ISSUE THREAD

**Issue by hojak99** [dig-is-life/Computer-Architecture#1]
### 컴퓨터 시스템의 개요
1. 컴퓨터 시스템
2. 컴퓨터 하드웨어
3. 컴퓨터 소프트웨어
4. 운영체제와 부팅
5. 컴파일러와 인터프리터
6. 컴퓨터의 분류
7. 컴퓨터의 구조, 구성, 실현
8. 하드웨어와 소프트웨어의 상호 조정

**Comment by jwqe764241** [comment]
이야~ 야근이다!
![6895db17d1b1fe102ca1890f97a84d8d76ac957e6ed99234ed874fc69cc2675f13b84ad9ff3bac38d15f680d56ed5d122c95582455f870a825b6b34665c03a04c0a7d896da87991ac95b114eeec808a62eab32cc3402979f75d106ccb7e5b7b1](https://user-images.githubusercontent.com/13945127/51841593-60cf4e80-2352-11e9-9137-2b89b0f14469.png)

**Comment by hojak99** [comment]
2월 4일 날까지  `챕터 1.md` 파일 업로드 후 2월 11일 날에 `챕터 2, 3.md` 파일 올리고 2월 11일 날 챕터1, 챕터2, 챕터 3에 대해서 얘기하는 것으로 함.

(설날 연휴로 인해)

**Comment by hojak99** [comment]
기한 내에 모두 마크다운 업로드 완료. 2월 11일 날 해당 정리한 내용을 토대로 이야기를 진행 후 이슈 닫도록 할 예정.
